import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import CartProvidersComp from "@/providers/CartProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark overflow-hidden h-screen`}>
        <div className="flex flex-col h-full w-full ">
          <Navbar />
          <div className="flex w-full h-full gap-4">
            <div className="flex-[1] hidden md:block">
              <Sidebar />
            </div>
            <CartProvidersComp>
              <div className="flex-[5] overflow-y-scroll">{children}</div>
            </CartProvidersComp>
          </div>
        </div>
      </body>
    </html>
  );
}
